### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib' on joblib.load

### ISSUE THREAD

**Issue by gitgithan** [hundredblocks/ml-powered-applications#15]
I'm trying to run train_simple_model.ipynb and already seen the `ImportError: cannot import name 'joblib' from 'sklearn.externals'`, so I installed and upgraded joblib to 1.01 and did `import joblib` directly which cleared that error. 

However, in the first cell, the code is failing through this path: from ml_editor.model_v1 import get_model_probabilities_for_input_texts --> VECTORIZER = joblib.load(curr_path / vectorizer_path) --> obj = _unpickle(fobj, filename, mmap_mode) --> obj = unpickler.load() --> dispatch[key[0]](self) --> klass = self.find_class(module, name) --> __import__(module, level=0) --> ModuleNotFoundError: No module named 'sklearn.externals.joblib'. 

I suspect this has got to do with how `vectorizer_1.pkl` is created. Is it because `vectorizer_1.pkl` was saved with the old joblib, so when loading, it is asking for the old joblib library? 

I was trying to recreate the 3 models and 2 vectorizers using my new joblib, hoping that this error will go away, then realized from searching joblib.dump that I can't find where the models and vectorizers are created. It seems that `vectorizer_1.pkl` is only created at the end of `train_simple_model.ipynb` with `joblib.dump(vectorizer, vectorizer_path)` but it is already being used in the 1st cell of the notebook, leading to the error in this issue. 

Are those artifacts in models folder pre-trained somewhere already? If not, which notebooks generated them? (so i can run these notebooks on new libraries to create loadable versions of the pickles). I hope to go through these notebooks without downgrading libraries or pinning to old versions as that is not sustainable in the long run.

P.s I also saw a `ModuleNotFoundError: No module named 'sklearn.ensemble.forest'` when loading models, it's probably related to the pickled model being trained on an older scikit-learn API.

**Comment by hundredblocks** [comment]
Hi @gitgithan I'm sorry to hear that you've been having issues. I haven't been able to reproduce locally but this does look similar to another issue which was due to a jupyter notebook getting in a bad state (https://github.com/hundredblocks/ml-powered-applications/issues/12).

Would you be able to restart your notebook and see if this is still an issue?

If not, I'd recommend testing using the pinned versions in `requirements.txt`. 

To answer your question, the serialized `.pkl` files are created in the following notebooks:
- https://github.com/hundredblocks/ml-powered-applications/blob/master/notebooks/train_simple_model.ipynb
- https://github.com/hundredblocks/ml-powered-applications/blob/master/notebooks/second_model.ipynb
- https://github.com/hundredblocks/ml-powered-applications/blob/master/notebooks/third_model.ipynb

Hopefully this helps resolve your issue
